apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hr-app
  name: hr-app
  namespace: s-28
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app
  strategy: {}
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
