apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"hr-app"},"name":"hr-app","namespace":"s-28"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"hr-app"}},"strategy":{},"template":{"metadata":{"labels":{"app":"hr-app"}},"spec":{"containers":[{"image":"nginx:1.18","name":"nginx","ports":[{"containerPort":80}],"resources":{}}]}}},"status":{}}
    creationTimestamp: "2024-01-08T16:04:49Z"
    generation: 2
    labels:
      app: hr-app
    name: hr-app
    namespace: s-28
    resourceVersion: "4039465"
    uid: 58b299be-bbb6-486c-a4e5-3299870e68e1
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hr-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hr-app
      spec:
        containers:
        - image: nginx:1.18
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2024-01-08T16:04:49Z"
      lastUpdateTime: "2024-01-08T16:04:50Z"
      message: ReplicaSet "hr-app-7fbd85f4f6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-01-08T16:07:39Z"
      lastUpdateTime: "2024-01-08T16:07:39Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
