apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-08T15:33:07Z"
  labels:
    owner: hasanboy
    run: nginx2
  name: nginx2
  namespace: s-28
  resourceVersion: "4032930"
  uid: 4660c59c-07ca-4619-b08e-065007b869da
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx2
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5zc5s
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5zc5s
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:33:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:33:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:33:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:33:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://9dbde5b4ab11417c710c2ef4ec684c9e4efda3169ca70d41661abf7731a6c194
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:2bdc49f2f8ae8d8dc50ed00f2ee56d00385c6f8bc8a8b320d0a294d9e3b49026
    lastState: {}
    name: nginx2
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-08T15:33:08Z"
  hostIP: 95.217.7.185
  phase: Running
  podIP: 10.233.66.184
  podIPs:
  - ip: 10.233.66.184
  qosClass: BestEffort
  startTime: "2024-01-08T15:33:07Z"
